#!/bin/sh
set -eu

mysql --protocol=socket -uroot -p"${MYSQL_ROOT_PASSWORD}" <<EOSQL
CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\`
  DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS \`${DOCTOR_DB_NAME}\`
  DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS \`${IDENTITY_DB_NAME}\`
  DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS '${DB_USERNAME}'@'%' IDENTIFIED BY '${DB_PASSWORD}';
CREATE USER IF NOT EXISTS '${DOCTOR_DB_USERNAME}'@'%' IDENTIFIED BY '${DOCTOR_DB_PASSWORD}';
CREATE USER IF NOT EXISTS '${IDENTITY_DB_USERNAME}'@'%' IDENTIFIED BY '${IDENTITY_DB_PASSWORD}';

ALTER USER '${DB_USERNAME}'@'%' IDENTIFIED BY '${DB_PASSWORD}';
ALTER USER '${DOCTOR_DB_USERNAME}'@'%' IDENTIFIED BY '${DOCTOR_DB_PASSWORD}';
ALTER USER '${IDENTITY_DB_USERNAME}'@'%' IDENTIFIED BY '${IDENTITY_DB_PASSWORD}';

GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '${DB_USERNAME}'@'%';
GRANT ALL PRIVILEGES ON \`${DOCTOR_DB_NAME}\`.* TO '${DOCTOR_DB_USERNAME}'@'%';
GRANT ALL PRIVILEGES ON \`${IDENTITY_DB_NAME}\`.* TO '${IDENTITY_DB_USERNAME}'@'%';
FLUSH PRIVILEGES;
EOSQL
